### ISSUE TITLE
Anki-dev group closed?

### ISSUE THREAD

**Issue by heinemml** [anki/drive-sdk#24]
Hi,

this is not really code specific but I didn't know where else to ask.
The Anki-Dev Group (https://groups.google.com/a/anki.com/forum/#!forum/anki-dev)  is not accessible anymore. It asks me to join but denies access afterwards as it is limited to "accounts from this organisation" . Is this on purpose?

Cheers,
Michael

**Comment by heinemml** [comment]
It is open again.

**Comment by igloochef** [comment]
It seems to be closed again with the same issue.
