### ISSUE TITLE
Error: Discover primary services by UUID failed: Internal application error: I/O

### ISSUE THREAD

**Issue by BenDuan** [anki/drive-sdk#39]
Hello,

I try to communicate with anki-cars via bluetooth in raspberry pi 3. I am able to connect the car. But i have no callback when I write conmand.

pi@raspberrypi:~ $ sudo anki/drive-sdk/build/dist/bin/vehicle-scan 
LE Scan ...
C4:A8:F8:D1:CA:E4 Drive [v305f] (Unknown 2408)
pi@raspberrypi:~ $ sudo anki/drive-sdk/build/dist/bin/vehicle-tool --device=C48:F8:D1:CA:E4
[C4:A8:F8:D1:CA:E4][LE]> connect
Attempting to connect to C4:A8:F8:D1:CA:E4
Connection successful
Error: Discover primary services by UUID failed: Internal application error: I/O
[C4:A8:F8:D1:CA:E4][LE]> sdk-mode 1
[C4:A8:F8:D1:CA:E4][LE]> ping
[C4:A8:F8:D1:CA:E4][LE]> set-lights-pattern TAIL FLASH 1 6 15

Thanks for any help you can provide!

Sincerely,
Ben

**Comment by fidel1986** [comment]
Hi,

same problem here.
What was your solution?

**Comment by BenDuan** [comment]
You should reinstall BlueZ. The blog of **Jared Wolff** "Get Started with Bluetooth Low Energy on Linux" has a detailed introduction. You can find it through Google search.
